global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'stand'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'recording_service'
    scrape_interval: 5s
    static_configs:
      - targets: ['ova-recording-api:8081']
