// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	recording "github.com/ozonva/ova-recording-api/pkg/recording"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddEntities mocks base method.
func (m *MockRepo) AddEntities(entities []recording.Appointment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEntities", entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEntities indicates an expected call of AddEntities.
func (mr *MockRepoMockRecorder) AddEntities(entities interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEntities", reflect.TypeOf((*MockRepo)(nil).AddEntities), entities)
}

// DescribeEntity mocks base method.
func (m *MockRepo) DescribeEntity(entityId uint64) (*recording.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeEntity", entityId)
	ret0, _ := ret[0].(*recording.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeEntity indicates an expected call of DescribeEntity.
func (mr *MockRepoMockRecorder) DescribeEntity(entityId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeEntity", reflect.TypeOf((*MockRepo)(nil).DescribeEntity), entityId)
}

// GetAddedCount mocks base method.
func (m *MockRepo) GetAddedCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddedCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetAddedCount indicates an expected call of GetAddedCount.
func (mr *MockRepoMockRecorder) GetAddedCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddedCount", reflect.TypeOf((*MockRepo)(nil).GetAddedCount))
}

// ListEntities mocks base method.
func (m *MockRepo) ListEntities(limit, offset uint64) ([]recording.Appointment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntities", limit, offset)
	ret0, _ := ret[0].([]recording.Appointment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntities indicates an expected call of ListEntities.
func (mr *MockRepoMockRecorder) ListEntities(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntities", reflect.TypeOf((*MockRepo)(nil).ListEntities), limit, offset)
}
