// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/kafka.proto

package kafka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KafkaMessage_Kind int32

const (
	KafkaMessage_UNKNOWN KafkaMessage_Kind = 0
	KafkaMessage_CREATED KafkaMessage_Kind = 1
	KafkaMessage_UPDATED KafkaMessage_Kind = 2
	KafkaMessage_DELETED KafkaMessage_Kind = 3
)

// Enum value maps for KafkaMessage_Kind.
var (
	KafkaMessage_Kind_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATED",
		2: "UPDATED",
		3: "DELETED",
	}
	KafkaMessage_Kind_value = map[string]int32{
		"UNKNOWN": 0,
		"CREATED": 1,
		"UPDATED": 2,
		"DELETED": 3,
	}
)

func (x KafkaMessage_Kind) Enum() *KafkaMessage_Kind {
	p := new(KafkaMessage_Kind)
	*p = x
	return p
}

func (x KafkaMessage_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KafkaMessage_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kafka_proto_enumTypes[0].Descriptor()
}

func (KafkaMessage_Kind) Type() protoreflect.EnumType {
	return &file_api_kafka_proto_enumTypes[0]
}

func (x KafkaMessage_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KafkaMessage_Kind.Descriptor instead.
func (KafkaMessage_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_kafka_proto_rawDescGZIP(), []int{0, 0}
}

type KafkaMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     KafkaMessage_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=ova.recording.api.KafkaMessage_Kind" json:"kind,omitempty"`
	Producer string            `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	// Types that are assignable to Body:
	//	*KafkaMessage_Created
	//	*KafkaMessage_Updated
	//	*KafkaMessage_Deleted
	Body isKafkaMessage_Body `protobuf_oneof:"body"`
}

func (x *KafkaMessage) Reset() {
	*x = KafkaMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kafka_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KafkaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaMessage) ProtoMessage() {}

func (x *KafkaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_kafka_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaMessage.ProtoReflect.Descriptor instead.
func (*KafkaMessage) Descriptor() ([]byte, []int) {
	return file_api_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *KafkaMessage) GetKind() KafkaMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return KafkaMessage_UNKNOWN
}

func (x *KafkaMessage) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (m *KafkaMessage) GetBody() isKafkaMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *KafkaMessage) GetCreated() *AppointmentCreatedV1 {
	if x, ok := x.GetBody().(*KafkaMessage_Created); ok {
		return x.Created
	}
	return nil
}

func (x *KafkaMessage) GetUpdated() *AppointmentUpdatedV1 {
	if x, ok := x.GetBody().(*KafkaMessage_Updated); ok {
		return x.Updated
	}
	return nil
}

func (x *KafkaMessage) GetDeleted() *AppointmentDeletedV1 {
	if x, ok := x.GetBody().(*KafkaMessage_Deleted); ok {
		return x.Deleted
	}
	return nil
}

type isKafkaMessage_Body interface {
	isKafkaMessage_Body()
}

type KafkaMessage_Created struct {
	Created *AppointmentCreatedV1 `protobuf:"bytes,3,opt,name=created,proto3,oneof"`
}

type KafkaMessage_Updated struct {
	Updated *AppointmentUpdatedV1 `protobuf:"bytes,4,opt,name=updated,proto3,oneof"`
}

type KafkaMessage_Deleted struct {
	Deleted *AppointmentDeletedV1 `protobuf:"bytes,5,opt,name=deleted,proto3,oneof"`
}

func (*KafkaMessage_Created) isKafkaMessage_Body() {}

func (*KafkaMessage_Updated) isKafkaMessage_Body() {}

func (*KafkaMessage_Deleted) isKafkaMessage_Body() {}

type AppointmentCreatedV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId uint64 `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
}

func (x *AppointmentCreatedV1) Reset() {
	*x = AppointmentCreatedV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kafka_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppointmentCreatedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentCreatedV1) ProtoMessage() {}

func (x *AppointmentCreatedV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_kafka_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentCreatedV1.ProtoReflect.Descriptor instead.
func (*AppointmentCreatedV1) Descriptor() ([]byte, []int) {
	return file_api_kafka_proto_rawDescGZIP(), []int{1}
}

func (x *AppointmentCreatedV1) GetAppointmentId() uint64 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

type AppointmentUpdatedV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId uint64 `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
}

func (x *AppointmentUpdatedV1) Reset() {
	*x = AppointmentUpdatedV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kafka_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppointmentUpdatedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentUpdatedV1) ProtoMessage() {}

func (x *AppointmentUpdatedV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_kafka_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentUpdatedV1.ProtoReflect.Descriptor instead.
func (*AppointmentUpdatedV1) Descriptor() ([]byte, []int) {
	return file_api_kafka_proto_rawDescGZIP(), []int{2}
}

func (x *AppointmentUpdatedV1) GetAppointmentId() uint64 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

type AppointmentDeletedV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId uint64 `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
}

func (x *AppointmentDeletedV1) Reset() {
	*x = AppointmentDeletedV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_kafka_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppointmentDeletedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentDeletedV1) ProtoMessage() {}

func (x *AppointmentDeletedV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_kafka_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentDeletedV1.ProtoReflect.Descriptor instead.
func (*AppointmentDeletedV1) Descriptor() ([]byte, []int) {
	return file_api_kafka_proto_rawDescGZIP(), []int{3}
}

func (x *AppointmentDeletedV1) GetAppointmentId() uint64 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

var File_api_kafka_proto protoreflect.FileDescriptor

var file_api_kafka_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x2e, 0x61, 0x70, 0x69, 0x22, 0xf7, 0x02, 0x0a, 0x0c, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f,
	0x76, 0x61, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x56, 0x31, 0x48, 0x00, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x43, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x56, 0x31, 0x48, 0x00, 0x52, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x43, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x56, 0x31, 0x48,
	0x00, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x3a, 0x0a, 0x04, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c,
	0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x3d,
	0x0a, 0x14, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x56, 0x31, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3d, 0x0a,
	0x14, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x56, 0x31, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x61,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x14,
	0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x56, 0x31, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x61, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_kafka_proto_rawDescOnce sync.Once
	file_api_kafka_proto_rawDescData = file_api_kafka_proto_rawDesc
)

func file_api_kafka_proto_rawDescGZIP() []byte {
	file_api_kafka_proto_rawDescOnce.Do(func() {
		file_api_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_kafka_proto_rawDescData)
	})
	return file_api_kafka_proto_rawDescData
}

var file_api_kafka_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_kafka_proto_goTypes = []interface{}{
	(KafkaMessage_Kind)(0),       // 0: ova.recording.api.KafkaMessage.Kind
	(*KafkaMessage)(nil),         // 1: ova.recording.api.KafkaMessage
	(*AppointmentCreatedV1)(nil), // 2: ova.recording.api.AppointmentCreatedV1
	(*AppointmentUpdatedV1)(nil), // 3: ova.recording.api.AppointmentUpdatedV1
	(*AppointmentDeletedV1)(nil), // 4: ova.recording.api.AppointmentDeletedV1
}
var file_api_kafka_proto_depIdxs = []int32{
	0, // 0: ova.recording.api.KafkaMessage.kind:type_name -> ova.recording.api.KafkaMessage.Kind
	2, // 1: ova.recording.api.KafkaMessage.created:type_name -> ova.recording.api.AppointmentCreatedV1
	3, // 2: ova.recording.api.KafkaMessage.updated:type_name -> ova.recording.api.AppointmentUpdatedV1
	4, // 3: ova.recording.api.KafkaMessage.deleted:type_name -> ova.recording.api.AppointmentDeletedV1
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_kafka_proto_init() }
func file_api_kafka_proto_init() {
	if File_api_kafka_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_kafka_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KafkaMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_kafka_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppointmentCreatedV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_kafka_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppointmentUpdatedV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_kafka_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppointmentDeletedV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_kafka_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*KafkaMessage_Created)(nil),
		(*KafkaMessage_Updated)(nil),
		(*KafkaMessage_Deleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_kafka_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_kafka_proto_goTypes,
		DependencyIndexes: file_api_kafka_proto_depIdxs,
		EnumInfos:         file_api_kafka_proto_enumTypes,
		MessageInfos:      file_api_kafka_proto_msgTypes,
	}.Build()
	File_api_kafka_proto = out.File
	file_api_kafka_proto_rawDesc = nil
	file_api_kafka_proto_goTypes = nil
	file_api_kafka_proto_depIdxs = nil
}
